version: 0.2
phases:
  install:
    run-as: Linux-user-name
    on-failure: ABORT 
    runtime-versions:
      php: 8.2
    
   
  pre_build:
    on-failure: ABORT
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
    # steps:
  post_build:
    on-failure: ABORT
    commands:
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG